import 'dart:math';

String response = '''
[{"id":1,"question":"Winning Managers Premier League","answer":"Pep Guardiola"},
{"id":1,"question":"Winning Managers Premier League","answer":"Antonio Conte"},
{"id":1,"question":"Winning Managers Premier League","answer":"Claudio Ranieri"},
{"id":1,"question":"Winning Managers Premier League","answer":"José Mourinho"},
{"id":1,"question":"Winning Managers Premier League","answer":"Manuel Pellegrini"},
{"id":1,"question":"Winning Managers Premier League","answer":"Alex Ferguson"},
{"id":1,"question":"Winning Managers Premier League","answer":"Roberto Mancini"},
{"id":1,"question":"Winning Managers Premier League","answer":"Carlo Ancelotti"},
{"id":1,"question":"Winning Managers Premier League","answer":"Arsène Wenger"},
{"id":1,"question":"Winning Managers Premier League","answer":"Kenny Dalglish"},
{"id":1,"question":"Winning Managers Premier League","answer":"Jurgen Klopp"},
{"id":2,"question":"Balon Dor Winners","answer":"Lionel Messi"},
{"id":2,"question":"Balon Dor Winners","answer":"Cristiano Ronaldo"},
{"id":2,"question":"Balon Dor Winners","answer":"Michel Platini"},
{"id":2,"question":"Balon Dor Winners","answer":"Johan Cruyff"},
{"id":2,"question":"Balon Dor Winners","answer":"Marco van Basten"},
{"id":2,"question":"Balon Dor Winners","answer":"Franz Beckenbauer"},
{"id":2,"question":"Balon Dor Winners","answer":"Ronaldo"},
{"id":2,"question":"Balon Dor Winners","answer":"Alfredo Di Stéfano"},
{"id":2,"question":"Balon Dor Winners","answer":"Kevin Keegan"},
{"id":2,"question":"Balon Dor Winners","answer":"Karl-Heinz Rummenigge"},
{"id":2,"question":"Balon Dor Winners","answer":"Luis Suárez"},
{"id":2,"question":"Balon Dor Winners","answer":"Eusébio"},
{"id":2,"question":"Balon Dor Winners","answer":"Bobby Charlton"},
{"id":2,"question":"Balon Dor Winners","answer":"Raymond Kopa"},
{"id":2,"question":"Balon Dor Winners","answer":"Gerd Müller"},
{"id":2,"question":"Balon Dor Winners","answer":"Zinedine Zidane"},
{"id":2,"question":"Balon Dor Winners","answer":"Gianni Rivera"},
{"id":2,"question":"Balon Dor Winners","answer":"Ruud Gullit"},
{"id":2,"question":"Balon Dor Winners","answer":"Lothar Matthäus"},
{"id":2,"question":"Balon Dor Winners","answer":"Roberto Baggio"},
{"id":2,"question":"Balon Dor Winners","answer":"Hristo Stoichkov"},
{"id":2,"question":"Balon Dor Winners","answer":"Andriy Shevchenko"},
{"id":2,"question":"Balon Dor Winners","answer":"George Best"},
{"id":2,"question":"Balon Dor Winners","answer":"Allan Simonsen"},
{"id":2,"question":"Balon Dor Winners","answer":"Ronaldinho"},
{"id":2,"question":"Balon Dor Winners","answer":"Luka Modric"},
{"id":3,"question":"World Cup Winners","answer":"Brazil"},
{"id":3,"question":"World Cup Winners","answer":"Italy"},
{"id":3,"question":"World Cup Winners","answer":"Germany"},
{"id":3,"question":"World Cup Winners","answer":"Uruguay"},
{"id":3,"question":"World Cup Winners","answer":"Argentina"},
{"id":3,"question":"World Cup Winners","answer":"France"},
{"id":3,"question":"World Cup Winners","answer":"England"},
{"id":3,"question":"World Cup Winners","answer":"Spain"},
{"id":4,"question":"Real Madrid Captains","answer":"Arthur Johnson"},
{"id":4,"question":"Real Madrid Captains","answer":"José Giralt"},
{"id":4,"question":"Real Madrid Captains","answer":"Federico Revuelto"},
{"id":4,"question":"Real Madrid Captains","answer":"Luciano Lizárraga"},
{"id":4,"question":"Real Madrid Captains","answer":"José Berraondo"},
{"id":4,"question":"Real Madrid Captains","answer":"José María Castell"},
{"id":4,"question":"Real Madrid Captains","answer":"Santiago Bernabéu"},
{"id":4,"question":"Real Madrid Captains","answer":"Juan Monjardín"},
{"id":4,"question":"Real Madrid Captains","answer":"Perico Escobal"},
{"id":4,"question":"Real Madrid Captains","answer":"Félix Pérez"},
{"id":4,"question":"Real Madrid Captains","answer":"Félix Quesada"},
{"id":4,"question":"Real Madrid Captains","answer":"Eugenio Hilario"},
{"id":4,"question":"Real Madrid Captains","answer":"Leoncito"},
{"id":4,"question":"Real Madrid Captains","answer":"José Ramón Sauto"},
{"id":4,"question":"Real Madrid Captains","answer":"Juan Antonio Ipiña"},
{"id":4,"question":"Real Madrid Captains","answer":"Sabino Barinaga"},
{"id":4,"question":"Real Madrid Captains","answer":"Clemente Fernández"},
{"id":4,"question":"Real Madrid Captains","answer":"Luis Molowny"},
{"id":4,"question":"Real Madrid Captains","answer":"Miguel Muñoz"},
{"id":4,"question":"Real Madrid Captains","answer":"Juanito Alonso"},
{"id":4,"question":"Real Madrid Captains","answer":"José María Zárraga"},
{"id":4,"question":"Real Madrid Captains","answer":"Francisco Gento"},
{"id":4,"question":"Real Madrid Captains","answer":"Ignacio Zoco"},
{"id":4,"question":"Real Madrid Captains","answer":"Amancio"},
{"id":4,"question":"Real Madrid Captains","answer":"Pirri"},
{"id":4,"question":"Real Madrid Captains","answer":"Miguel Ángel"},
{"id":4,"question":"Real Madrid Captains","answer":"Santillana"},
{"id":4,"question":"Real Madrid Captains","answer":"José Antonio Camacho"},
{"id":4,"question":"Real Madrid Captains","answer":"Chendo"},
{"id":4,"question":"Real Madrid Captains","answer":"Manuel Sanchís"},
{"id":4,"question":"Real Madrid Captains","answer":"Fernando Hierro"},
{"id":4,"question":"Real Madrid Captains","answer":"Raúl"},
{"id":4,"question":"Real Madrid Captains","answer":"Iker Casillas"},
{"id":4,"question":"Real Madrid Captains","answer":"Sergio Ramos"},
{"id":5,"question":"Real Madrid Players Won World Cup","answer":"Günter Netzer"},
{"id":5,"question":"Real Madrid Players Won World Cup","answer":"Jorge Valdano"},
{"id":5,"question":"Real Madrid Players Won World Cup","answer":"Christian Karembeu"},
{"id":5,"question":"Real Madrid Players Won World Cup","answer":"Roberto Carlos"},
{"id":5,"question":"Real Madrid Players Won World Cup","answer":"Iker Casillas"},
{"id":5,"question":"Real Madrid Players Won World Cup","answer":"Raúl Albiol"},
{"id":5,"question":"Real Madrid Players Won World Cup","answer":"Xabi Alonso"},
{"id":5,"question":"Real Madrid Players Won World Cup","answer":"Sergio Ramos"},
{"id":5,"question":"Real Madrid Players Won World Cup","answer":"Alvaro Arbeloa"},
{"id":5,"question":"Real Madrid Players Won World Cup","answer":"Sami Khedira"},
{"id":5,"question":"Real Madrid Players Won World Cup","answer":"Raphaël Varane"}
]
''';

//print ("chosenid is $chosenid");
int min = 1;
int max = 5;
final rnd = new Random();
final int chosenid = min + rnd.nextInt(max - min);
